export const replayRedLogo = require('../images/replay-red-logo.png')
export const replayRedWordmark = require('../images/Replay_Wordmark_Red.png')
export const overlayImage = require('../images/overlay-640.jpg')
export const connectWithStrava = require('../images/btn_strava_connectwith_orange2x.png')
export const poweredByStrava = require('../images/api_logo_pwrdBy_strava_horiz_gray.png')
